# Universal prompt
format = "$username$hostname$all"

# Inserts a blank line between shell prompts
add_newline = false 

# Make prompt single line
[line_break]
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✖](bold red)"

# Username
[username]
format = "[$user]($style)@"
style_root = "bold #ff0000"
style_user = "fg:#00ffff"
show_always = true

# Hostname (computer name)
[hostname]
format = "[$hostname]($style) in "
style = "fg:#fe015a"
ssh_only = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
